
export const SELECT_CASE = "CASE_SELECTED";
export const UNSELECT_CASE = "UNSELECT_CASE";
export const SAVE_CASE_CONTENT = "SAVE_CASE_CONTENT";
export const DELETE_CASE_CONTENT = "DELETE_CASE_CONTENT";
export const EDIT_CASE="EDIT_CASE";